%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% system_configuration_pendulum.m
% Configuration file for the whole system, including
% processors, applications, tasks, messages
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TTW use case: pendulum network
% - 5 pendulums with one remote controller (6 nodes)
% - 2 "real-time-processes" with one remote controller (3 nodes)
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Romain Jacob, last update 18.06.19
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Log
%
% 18.06.19:
%  + Modify the format of the file for improved usability
% 
% 19.06.16:
%  + added support for custom constraints

%% TODO 
% + document how the custom constraints are formulated, and their meaning

%%
% configuration of processors
% Tuple: 
% - API_ID = 1: ID - ***empty by initial configuration
% - API_NM = 2: Name
% - API_MP = 3: Mapping - ***empty by initial configuration
% - API_CP = 4: Collision Pairs - ***empty by initial configuration
% AP1 = {1,'AP_real1',{},{}};
% AP2 = {2,'AP_real2',{},{}};
% AP3 = {3,'AP_sim3',{},{}};
% AP4 = {4,'AP_sim4',{},{}};
% AP5 = {5,'AP_sim5',{},{}};
% AP6 = {6,'AP_ctrl',{},{}};
% AP7 = {7,'AP_rt_1',{},{}};
% AP8 = {8,'AP_rt_2',{},{}};
% AP9 = {9,'AP_rt_ctrl',{},{}};
APs = {...
    { [],'AP_real1',{},{} }, ...
    { [],'AP_real2',{},{} }, ...
    { [],'AP_sim3',{},{} }, ...
    { [],'AP_sim4',{},{} }, ...
    { [],'AP_sim5',{},{} }, ...
    { [],'AP_ctrl',{},{} }, ...
    { [],'AP_rt_1',{},{} }, ...
    { [],'AP_rt_2',{},{} }, ...
    { [],'AP_rt_ctrl',{},{} }, ...
    };
   
%%
% configuration of tasks
% Tuple: 
% - TI_ID = 1: ID ***empty by initial configuration
% - TI_NM = 2: Name                     /!\ --- MUST START WITH 'T' --- /!\
% - TI_MP = 3: Mapping
% - TI_ET = 4: Execution Time
% - TI_PD = 5: Period - ***-1 by initial configuration
% - TI_NI = 6: Number of Instances - ***-1 by initial configuration

Tasks = { ...
 { [],  'T_fetch_sens1',  'AP_real1',   1,-1,-1}, ...
 { [],  'T_fetch_sens2',  'AP_real2',   1,-1,-1}, ...
 { [],  'T_fetch_sens3',  'AP_sim3',    1,-1,-1}, ...
 { [],  'T_fetch_sens4',  'AP_sim4',    1,-1,-1}, ...
 { [],  'T_fetch_sens5',  'AP_sim5',    1,-1,-1}, ...
 { [],  'T_sync_ctrl1',   'AP_real1',   3,-1,-1}, ...
 { [],  'T_sync_ctrl2',   'AP_real2',   3,-1,-1}, ...
 { [],  'T_sync_ctrl3',   'AP_sim3',    3,-1,-1}, ...
 { [],  'T_sync_ctrl4',   'AP_sim4',    3,-1,-1}, ...
 { [],  'T_sync_ctrl5',   'AP_sim5',    3,-1,-1}, ...
 };
     

%%
% configuration of messages
% Tuple: 
% - MI_ID = 1: ID 
% - MI_NM = 2: Name                     /!\ --- MUST START WITH 'M' --- /!\
% - MI_PD = 3: Period - ***-1 for initial configuration
% - MI_NI = 4: Number of instances - ***-1 for initial configuration
% - MI_LD = 5: Load(numer of slots needed)
Msgs = { ...
 { [],  'M_sync1',      -1,-1,1}, ...
 { [],  'M_sync2',      -1,-1,1}, ...
 { [],  'M_sync3',      -1,-1,1}, ...
 { [],  'M_sync4',      -1,-1,1}, ...
 { [],  'M_sync5',      -1,-1,1}, ...
 };

%%
% configuration of applications
% Tuple: 
% - AI_ID = 1: ID 
% - AI_NM = 2: Name
% - AI_PD = 3: Period
% - AI_DL = 4: Deadline
% - AI_TC = 5: Task chain
% - AI_NI = 6: Numer of instances - ***empty by initial configuration

APPs = { ...
 { [],  'a_sync1', 100, 60, {'T_fetch_sens1','M_sync1','T_sync_ctrl1'}}, ...
 { [],  'a_sync2', 100, 60, {'T_fetch_sens2','M_sync2','T_sync_ctrl2'}}, ...
 { [],  'a_sync3', 100, 60, {'T_fetch_sens3','M_sync3','T_sync_ctrl3'}}, ...
 { [],  'a_sync4', 100, 60, {'T_fetch_sens4','M_sync4','T_sync_ctrl4'}}, ...
 { [],  'a_sync5', 100, 60, {'T_fetch_sens5','M_sync5','T_sync_ctrl5'}}, ...
 };      

%%
% Custom constraints

CustomConstaints = { ...
    { {{'T_fetch_sens1', 1},{'T_fetch_sens2', -1}}, '=', 0}, ...
    { {{'T_fetch_sens1', 1},{'T_fetch_sens3', -1}}, '=', 0}, ...
    { {{'T_fetch_sens1', 1},{'T_fetch_sens4', -1}}, '=', 0}, ...
    { {{'T_fetch_sens1', 1},{'T_fetch_sens5', -1}}, '=', 0}, ...
    };




